[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "configat"
version = "0.1.1"

[project.optional-dependencies]
parser = ["tabulate", "pathspec"]

[tool.setuptools]
packages = ["configat"]

[tool.coverage.report]
exclude_also = ["@typing.overload"]
